---
title: "Cover Letter"
author: "Caity Johnson"
date: "1/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Two years ago, as I was preparing to graduate from Gaston College with my Associate of Science degree, I was faced with deciding my future college career.The reasons for choosing Appalachian State over all other schools to transfer to in the fall of 2018 were heavily based on the Accelerated Admissions Program (4+1). After lengthy discussions with professors from Gaston College and App St, I chose this university as the place to advance my collegiate career.  The 4+1 program and my tutoring opportunities will allow me to graduate from App St and return to Gaston College to pursue a career as an instructor in mathematics.  
	
The 4+1 program allows me to continue my college experience in the community and university system that I feel is a perfect fit to my values, needs, and goals.  After spending my Junior year on the mountain, I now feel like Boone is home, and will always be a major part of my life.  As a child of two Navy parents, I have experienced many moves, and attended numerous high schools.  I appreciate more than most people just how important it is to have the opportunity to dig in, and have a place like Boone and App St to begin my professional career.  

In my high school career, I transferred schools five times, attending four different schools. From this experience, I was able to learn to make connections with others easier and create a demeanor where others knew that they could trust me. This has allowed me to create welcoming environments for my peers, coworkers and strangers. Mother Teresa's quote describes me as a person the best because I always have a smile on my face and am always trying to brighten other's days: "every time you smile at someone, it is an action of love, a gift to that person, a beautiful thing." I cannot think of a time where I made others uncomfortable with the expressions on my face or my body language. 
	
The importance of having a seamless transition from my bachelor to masters degree is that the 4+1 program allows me to stay on track with the timeline I set for myself when I chose App St two years ago.  The professors and staff at Gaston College have expressed an incredible interest in my return to the campus as a new professor.  As a member of the 4+1 program, I will achieve at every opportunity in the class and in my professional growth.  
	
Thank you for consideration into this extraordinary program. Please know that I value this opportunity, and understand that I will be working hard everyday to complete and utilize my Master in Mathematics degree. I look forward to beginning the program in the summer as a member of the class of 2021.
