---
title: "Caitlyn A. Johnson"
output: html_document
---

#### Personal Email

[ctlnjohnson@gmail.com](https://mail.google.com/mail/u/0/)

#### School Email

[johnsonca18@appstate.edu](https://mail.google.com/mail/u/1/)


# Skills

* Excellent communicator
* Work well with others as well as by myself
* Quick learner
* Great adaptability

# Education

#### High School:

* **Paxon School for Advanced Studies**, *Jacksonville, Fl*: 08/2012 - 01/2015
* **Bessemer City High School**, *Bessemer City, NC*: 02/2015 - 03/2015, 08/2015 - 01/2016
* **Robert E. Lee High School**, *Jacksonville, Fl*: 03/2015 - 06/2015
* **North Gaston High School**, *Dallas, NC*: 01/2016 - 06/2016

#### College:

* **Gaston College**, *Dallas, NC*
    + Associates of Science Degree
        + President of Gaston College Math Club
            + Represented Gaston College in numerous inter-collegiate math competitions.
            
* **Appalachian State University**, *Boone, NC*
    + Class of 2020
    +	Mathematics with Concentration in Statistics 
        + Math Club Member
        
# Courses Related to Degree

* Data Science
* Statistical Data Analysis
* Statistical Methods I & II
* Linear Algebra
* Differential Equations
* Calculus I-III
* Techniques of Proof
* Real Analysis
* Numerical Methods
* Probability

# Professional Job Experience

**Cracker Barrel**

October 2016 - July 2019

*	Developed customer relation skills as server and host.
*	Achieved status of Certified Trainer for all newly hired and subordinate host employees.
*	Served as lead host on duty for all shifts.
*	Ensured host staff, and other employees worked efficiently together throughout shift.
*	Acted in management’s absence to resolve customer disputes and ensure customer satisfaction.
*	Assisted servers in peak customer times, and low staffed shifts.

**Gaston College**

January 2018 - July 2019

*	Tutored college students in various subjects (English, Math, & Physics).
*	Assisted professors and staff with various tasks during class presentations.  

**Appalachian State**

September 2019 - Present

* Tutor App State students in the General Mathematics and Physics labs.