---
title: "Skills Explained"
output: html_document
---

A skill that I have acquired over the years is being able to adapt to changing situations. My mother joined the Navy right after the start of my 8th grade year. She was stationed in Jacksonville, Florida and we moved there on November 11, 2011. With it being in the middle of the school year, I had to learn to make friends fast. At my previous school, we had grown up together so everyone knew each other. Due to this, I had never had to make new friends or really talk to new people, so I thought I would have a difficult time. However, I quickly realized that I was greatly mistaken. I made friends within the first day of being at the school. 

In 9th grade, I switched to a different county in Jacksonville because we moved from an apartment to a house on Naval Air Station Jacksonville. Now again, I had to make a brand new group of friends. This was slightly more difficult because by high school everyone has their own set group of friends. Despite people not being as open, I was able to make friends within the first week. 

In the second half of my junior year of high school, I switched schools 3 times. This was especially difficult because I did not only switch school districts, but I moved from Florida to North Carolina and then back to Florida. While for others, this would seem difficult, for me it was quite an easy transition despite having to move states twice within 1 month. I was only at the NC school for 3 weeks. The first high school I attended in Florida was a "magnet school" which means that it is the best of the best. At one point, it was in the top 50 schools in the nation. Because of this, I was not able to transfer back into the school due to them only accepting students at the beginning of each year, so I had to move to a different school. Here again, I had to adapt to the new environment of a different school. 

In my senior year, I moved back to NC to the school I had previously attended for 3 weeks. Over Christmas break we moved to a different school district, so I had to change schools for the fifth time. Due to all of the rearranging and moving, I have become well prepared to changing situations. These circumstances has improved my communication skills which in turn has also allowed me to develop strong and constructive work relationships. 